# here momery and cpu limit and request
    
kubectl delete quota resourcequota_name

INSIDE POD LIMITS AND REQUEST DEFINE
apiVersion: v1
kind: Pod
metadata:
  name: mywebapp1
  namespace: myns
  labels:
    role: webserver-role
    app: nginx
spec:
  containers:
  - name: webserver1
    image: nginx:1.6
    resources:
    limits:
      memory: 512Mi                           # maximum memory
      cpu: 1                                  # 1 = 1000 mili cpu, maximum cpu
    requests:
      memory: 256Mi                            # its pod minimum use 256 mb memory
      cpu: 0.5                                 # its pod minimum use 500 mili cpu

RESOUCRE QUOTA FOR FULL NAMESPACES = limit for full namespace memory and cpu and cpu
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-high
  spec:
    hard:
      cpu: "1000"                               # maximum cpu you can use in this ns
      memory: 200Gi                            # maximum memory you can use in this ns
      pods: "10"                               # maximum pod you can create in this ns
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["high"]
        
kubectl apply -f file_name.yml -n namespace_name

WHEN SOME POD and conatiner IS CREATE BY DEFAULT RESOUCRE REQUEST AND LIMIT SET

kubectl get limits -n namespace_name                                     # its limits of namespace
kubectl get limitrange -n namespace_name    

yaml file
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: myns
spec:
  limits:
  - default:                            
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 256Mi
      cpu: 100m
    min:                         # minmum etni te milna hi cheya and always this value smaller than deaultrequest
      cpu: 80m
      memory: 50Mi
    max:                          # maximum enti hi mila  and always this value larger than default
      cpu: 300m
      memory: 1000Mi 
    type: Container
    
    #max limit /request ratio =  # then limit divide request it its value more than 2 then its not creating pod
    
    apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: myns
spec:
  limits:
    - maxLimitRequestRatio:                           # then limit divide request it its value more than 2 then its not creating pod
        memory: 2
      type: Container
