apiVersion: V1
kind: Pod
metadata:
  name: myfirstpod
  labels: 
    env: pod
    
spec:
  containers:
    - name: container_name
      image: image_name
      env:                                            # environment variable define
        - name: myname
          value: Anshul
        - name: city
          value: Pathankot
      args: ["sleep", "50"]                            # run this command when conatiners start
    - name: second_container                            # second conatiner
      image: image_name
      
