apiVersion: V1
kind: Pod
metadata:
  name: myfirstpod
  labels: 
    env: pod
    
spec:
  containers:
    - name: container_name
      image: image_name
      env:                                            # environment variable define
        - name: myname
          value: Anshul
        - name: city
          value: Pathankot
      
